/**
 * build-wechat.js
 * 把模块化源码打包成微信小游戏可运行的【单文件】game.js（IIFE，无 import/export）。
 *
 * 用法：npm run build:wechat
 *
 * 产出：
 *   game.js                 — 微信入口（单文件打包）
 *   dist/wechat/            — 可直接导入开发者工具的干净项目
 *   dist/HellRift.zip       — 上述目录的压缩包
 */

import * as esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

async function main() {
  const outfile = path.join(root, 'game.js');

  await esbuild.build({
    entryPoints: [path.join(root, 'src', 'wechat-entry.js')],
    bundle: true,
    outfile,
    format: 'iife',
    platform: 'neutral',
    target: ['es2017'],
    minify: false,
    sourcemap: false,
    logLevel: 'info',
    banner: {
      js: '/* HellRift WeChat bundle — generated by npm run build:wechat. DO NOT EDIT. */\n',
    },
  });

  execFileSync(process.execPath, ['--check', outfile], { stdio: 'inherit' });

  // 组装干净的微信导入目录（绝不包含 src/ scripts/ index.html 等）
  const wechatDir = path.join(root, 'dist', 'wechat');
  fs.rmSync(wechatDir, { recursive: true, force: true });
  fs.mkdirSync(wechatDir, { recursive: true });

  fs.copyFileSync(outfile, path.join(wechatDir, 'game.js'));
  fs.copyFileSync(path.join(root, 'game.json'), path.join(wechatDir, 'game.json'));

  const projectConfig = {
    description: '地狱裂隙 Hell Rift - 微信小游戏（单文件打包版）',
    setting: {
      es6: true,
      enhance: true,
      postcss: false,
      minified: false,
      newFeature: true,
    },
    compileType: 'game',
    appid: 'touristappid',
    projectname: 'HellRift',
    miniprogramRoot: './',
    srcMiniprogramRoot: './',
  };
  fs.writeFileSync(
    path.join(wechatDir, 'project.config.json'),
    JSON.stringify(projectConfig, null, 2),
  );

  fs.writeFileSync(
    path.join(wechatDir, '导入说明.txt'),
    [
      '地狱裂隙 Hell Rift — 微信使用说明',
      '',
      '【第一次导入】',
      '1. 用微信开发者工具「新建小游戏」',
      '2. 目录选择本文件夹（有 game.js / game.json，没有 src/）',
      '3. AppID 选择「测试号」→ 创建 → 编译',
      '',
      '【以后更新 —— 不用重新导入！】',
      '方式 A（推荐）：双击运行「更新游戏.bat」，成功后回开发者工具点「编译」',
      '方式 B：浏览器打开下面链接，另存为覆盖本目录的 game.js，再点「编译」',
      '  https://raw.githubusercontent.com/Xingyu-TUe/3D-Agent/cursor/hell-rift-wechat-game-b0ee/game.js',
      '',
      '只要项目还开着，替换 game.js 后点编译即可，不必反复「下载 zip → 新建项目」。',
      '',
      '本包为单文件打包版。鼠标按住模拟器左半屏 = 摇杆。',
      '',
    ].join('\n'),
  );

  // 一键更新脚本（Windows）
  const batSrc = path.join(root, 'scripts', 'wechat-update', '更新游戏.bat');
  if (fs.existsSync(batSrc)) {
    fs.copyFileSync(batSrc, path.join(wechatDir, '更新游戏.bat'));
  }

  // 打 zip（临时用 HellRift 目录名）
  const dist = path.join(root, 'dist');
  const hellDir = path.join(dist, 'HellRift');
  fs.rmSync(hellDir, { recursive: true, force: true });
  fs.cpSync(wechatDir, hellDir, { recursive: true });

  const zipPath = path.join(dist, 'HellRift.zip');
  fs.rmSync(zipPath, { force: true });
  execFileSync('zip', ['-rq', zipPath, 'HellRift'], { cwd: dist });
  fs.rmSync(hellDir, { recursive: true, force: true });

  const size = fs.statSync(zipPath).size;
  const gameSize = fs.statSync(outfile).size;
  console.log(`[HellRift] game.js 打包完成 (${Math.round(gameSize / 1024)} KB)`);
  console.log(`[HellRift] 微信包: dist/HellRift.zip (${Math.round(size / 1024)} KB)`);
  console.log('[HellRift] 导入目录: dist/wechat/');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
