/**
 * build-wechat.js
 * 把模块化源码打包成微信小游戏可运行的【单文件】game.js（IIFE，无 import/export）。
 *
 * 用法：npm run build:wechat
 *
 * 产出：
 *   game.js                 — 微信入口（单文件打包）
 *   dist/wechat/            — 可直接导入开发者工具的干净项目
 *   dist/HellRift.zip       — 上述目录的压缩包
 */

import * as esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

async function main() {
  const outfile = path.join(root, 'game.js');

  await esbuild.build({
    entryPoints: [path.join(root, 'src', 'wechat-entry.js')],
    bundle: true,
    outfile,
    format: 'iife',
    platform: 'neutral',
    target: ['es2017'],
    minify: false,
    sourcemap: false,
    logLevel: 'info',
    banner: {
      js: '/* HellRift WeChat bundle — generated by npm run build:wechat. DO NOT EDIT. */\n',
    },
  });

  execFileSync(process.execPath, ['--check', outfile], { stdio: 'inherit' });

  // 组装干净的微信导入目录（绝不包含 src/ scripts/ index.html 等）
  const wechatDir = path.join(root, 'dist', 'wechat');
  fs.rmSync(wechatDir, { recursive: true, force: true });
  fs.mkdirSync(wechatDir, { recursive: true });

  fs.copyFileSync(outfile, path.join(wechatDir, 'game.js'));
  fs.copyFileSync(path.join(root, 'game.json'), path.join(wechatDir, 'game.json'));

  // 贴图目录（运行时按 Assets/ 相对路径加载，不内联进 game.js）
  const assetsSrc = path.join(root, 'src', 'Assets');
  const assetsDst = path.join(wechatDir, 'Assets');
  const assetsRoot = path.join(root, 'Assets');
  if (fs.existsSync(assetsSrc)) {
    fs.cpSync(assetsSrc, assetsDst, { recursive: true });
    // 同步到仓库根，避免误开源码目录时找不到 Assets/
    fs.rmSync(assetsRoot, { recursive: true, force: true });
    fs.cpSync(assetsSrc, assetsRoot, { recursive: true });
    const charDir = path.join(assetsDst, 'characters');
    if (fs.existsSync(charDir)) {
      console.log('[HellRift] 已包含 8 向角色动画包 characters/{druid,hunter,mage}/');
    }
  } else {
    console.warn('[HellRift] 缺少 src/Assets，请先 npm run generate:all');
  }

  const projectConfig = {
    description: '地狱裂隙 Hell Rift - 微信小游戏（单文件打包版）',
    setting: {
      es6: true,
      enhance: true,
      postcss: false,
      minified: false,
      newFeature: true,
    },
    compileType: 'game',
    appid: 'touristappid',
    projectname: 'HellRift',
    miniprogramRoot: './',
    srcMiniprogramRoot: './',
  };
  fs.writeFileSync(
    path.join(wechatDir, 'project.config.json'),
    JSON.stringify(projectConfig, null, 2),
  );

  fs.writeFileSync(
    path.join(wechatDir, '导入说明.txt'),
    [
      '地狱裂隙 Hell Rift — 微信使用说明',
      '',
      '【第一次导入】',
      '1. 只下载 / 解压 dist/HellRift.zip（不要直接打开整个 GitHub 源码仓库）',
      '2. 解压后得到 HellRift 文件夹，里面应直接看到：',
      '     game.js   game.json   project.config.json   Assets/',
      '3. 微信开发者工具 → 导入 / 新建小游戏 → 目录选这个 HellRift 文件夹',
      '4. AppID 选「测试号」→ 编译',
      '',
      '【控制台报 Assets 加载失败 / 预加载 0/42】',
      '原因：当前打开的目录里没有 Assets/（常见于误开了带 src、index.html 的源码根目录）。',
      '解决：',
      'A. 关掉项目，重新导入 HellRift.zip 解压出的 HellRift 文件夹（推荐）',
      'B. 若坚持用源码目录：双击「修复Assets.bat」，或把 src\\Assets 复制成根目录 Assets\\',
      'C. 双击「更新游戏.bat」会同时拉 game.js + Assets',
      '',
      '【红色 FileUtils / PreCompile 一长串】',
      '多半是打开了错误目录（整个仓库）。请只导入 HellRift.zip 那一层。',
      '',
      '【以后更新】',
      '双击「更新游戏.bat」→ 回开发者工具点「编译」。',
      '',
      '本包 = 单文件 game.js + Assets 贴图。左半屏按住 = 摇杆。',
      '',
    ].join('\n'),
  );

  // Windows 辅助脚本
  const updateDir = path.join(root, 'scripts', 'wechat-update');
  for (const name of ['更新游戏.bat', '检查项目.bat', '修复Assets.bat']) {
    const src = path.join(updateDir, name);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(wechatDir, name));
  }

  // 打 zip（临时用 HellRift 目录名）
  const dist = path.join(root, 'dist');
  const hellDir = path.join(dist, 'HellRift');
  fs.rmSync(hellDir, { recursive: true, force: true });
  fs.cpSync(wechatDir, hellDir, { recursive: true });

  const zipPath = path.join(dist, 'HellRift.zip');
  fs.rmSync(zipPath, { force: true });
  execFileSync('zip', ['-rq', zipPath, 'HellRift'], { cwd: dist });
  fs.rmSync(hellDir, { recursive: true, force: true });

  const size = fs.statSync(zipPath).size;
  const gameSize = fs.statSync(outfile).size;
  console.log(`[HellRift] game.js 打包完成 (${Math.round(gameSize / 1024)} KB)`);
  console.log(`[HellRift] 微信包: dist/HellRift.zip (${Math.round(size / 1024)} KB)`);
  console.log('[HellRift] 导入目录: dist/wechat/');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
